### PR TITLE
Array convenience methods

### PR DESCRIPTION
**Pull request by zhuker**
Added convenience methods to Array class.

before:

```
$array(“a1”, “b1”, “a2”).filter((item, index, array) -> item.startsWith(“a”));
```

after:

```
$array(“a1”, “b1”, “a2”).filter(item -> item.startsWith(“a”));
```

same for map, reduce, reduceRight, filter, every, some

### CODE REVIEW

**Comment by zhuker** [comment]
build fails because of 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project stjs: Exit code: 2 -> [Help 1]
```
should i disable it?

**Comment by zhuker** [comment]
hello?

**Comment by acraciun** [comment]
Hi @zhuker,

I'm sorry for the time it takes to answer - we're currently spending time to see if TypeScript is or not a better fit.
The error that you have is because of the password needed by nexus maven central when you release. You should not have this error is you simply build a snapshot.

**Comment by zhuker** [comment]
@acraciun i definitely can release as snapshot, i am providing this PR as a contribution to st-js

**Comment by zhuker** [comment]
typescript is a better fit if you have a javascript-only project
st-js on the other hand, helps us bridge java backend and js frontend

**Comment by zhuker** [comment]
@acraciun is this PR not interesting for the project?

**Comment by acraciun** [comment]
sure thank you.
it was not initially merged automatically because it seems that the automatic check of travis did not work ...

**Pull request merged**
